[package]
name = "s3-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-sdk-s3 = { workspace = true, features = ["behavior-version-latest"] }
backon = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
