[package]
name = "s3-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-sdk-s3 = { version = "1.83.0", features = ["behavior-version-latest"] }
backon = "1.5.0"
futures = "0.3.31"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
